config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
    resources :reviews, onlyly: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
  has_many :cocktails, through: :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show; end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path(@cocktails)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, except: [:destroy]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail), notice: 'Dose was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail), notice: 'Dose was successfully destroyed.'
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail, except: [:destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])

    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail), notice: 'Review was successfully destroyed.'
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="cards-container-new">
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<%= link_to 'Back', cocktails_path %>

</div>

app/views/cocktails/backgroundimage.html.erb
  <div class="card-self">
  <% if @cocktail.photo.attached? == true %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
        <%= cocktail.name %>
      </div>
  <% else %>
  <% end %>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-6">
        <%= "Lorem ipsum dolor sit amet, consectetur adipisicing elit " * 100 %>
      </div>
    </div>
  </div>


<!-- Need to do:
1. DONE seed for ingredients DONE
2. DONE type.js DONE
3. NOT WORKING select2 UNDONE
4. NO NEED sweetalert PRIORITY LOW
5. SIZE STRANGE cards for each cocktail
5a.opacity to the background or font more visible or pre-opacity image reupload
6. DONE picture for each cocktail as background img
7. DONE JS proper navbar with cocktails and add cocktail
8. DONE review model+controller
9. review count on the index.html represented as an icon
10.DONE add destroy for cocktail and add them to the show
11.add at show a scrolling-wrapper with samples
12.JS animation for cards when hover & scrolling down
13.JS animation when first(if possible) loading index page with smooth transition
14.add small footer -->

app/views/cocktails/buttons.html.erb
<!-- Not beeing used. only testing -->


    <%= link_to new_cocktail_path, class: "cybr-btn" do %>Add Cocktail<span aria-hidden>_</span>
    <span aria-hidden class="cybr-btn__glitch">Add Cocktail_</span>
    <span aria-hidden class="cybr-btn__tag">404</span>
    <% end %>
    <%= link_to 'Add Cocktail', new_cocktail_path, class: "btn btn-outline-primary" %>

app/views/cocktails/index.html.erb
<!-- <div class="first_header"> -->
  <div class="banner">
    <h1>Cyber77Cocktails</h1>
    <!-- add add cocktail to it -->
    <p>
      <span id="banner-typed-text"></span>
    </p>
  </div>

  <div class="cards-container">
  <h2 class="all_cocktails">Cyber Cocktail List</h2>
    <div class="cards">
      <% @cocktails.each do |cocktail| %>
      <!-- <div class="card-self"> -->
      <div class="card-self">
        <% if cocktail.photo.attached? == true %>
        <div class="card-background-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.photo.key, height: 400, width: 300, crop: :fill %>)">
        <% end %>
          <h5><%= link_to cocktail.name, cocktail_path(cocktail.id) %></h5>
            <td>

            </td>
        </div>
      </div>
      <% end %>
    </div>
  </div>



  <!-- <div>
    <button class="cybr-btn">
      New Cocktail<span aria-hidden>_</span>
      <span aria-hidden class="cybr-btn__glitch">New Cocktail_</span>
      <span aria-hidden class="cybr-btn__tag">404</span>
    </button>
    <button class="cybr-btn">
      DESTROY<span aria-hidden>_</span>
      <span aria-hidden class="cybr-btn__glitch">DESTROY_</span>
      <span aria-hidden class="cybr-btn__tag">500</span>
    </button>
  </div> -->
<!-- </div> -->

app/views/cocktails/new.html.erb
<div class="banner">
  <h1>Add Cocktail</h1>
</div>
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<div class="banner">
  <h1>Cocktail</h1>
</div>

<div class="cards-container">
  <p id="notice"><%= notice %></p>
  <div class="cards-show">
  <% if @cocktail.photo.attached? == true %>
    <div class="card-background-image-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @cocktail.photo.key, height: 400, width: 300, crop: :fill %>)"></div>
  <% end %>
    <div class="card-content">
      <p>
        <strong>Name:</strong>
        <%= @cocktail.name %><%= link_to "💥",
            cocktail_path(@cocktail),
            method: :delete,
            data: { confirm: "Are you sure you want to delete it?" } %>
      </p>

      <ul class="list-group">
        <% @cocktail.doses.each do |dose| %>
          <li><%= dose.ingredient.name %></li>
          <li class="list-group-item-self"><%= dose.description %> <%= link_to "Remove",
            dose_path(dose),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
          </li>
        <% end %>
      </ul>
      <% if @cocktail.reviews.exists? %>
      <p>Review:</p>
      <ul class="list-group">
        <% @cocktail.reviews.each do |review| %>
          <li class="list-group-item-self"><%= review.content %> <%= link_to "💥",
            review_path(review),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
          </li>
        <% end %>
      </ul>
      <% end %>
      <div>
        <%= link_to 'Leave a review', new_cocktail_review_path(@cocktail) %>
      </div>
      <div>
        <%= link_to 'Add Dose', new_cocktail_dose_path(@cocktail) %>
      </div>
      <div>
        <%= link_to 'Back', cocktails_path %>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="banner">
  <h1>Add Dose</h1>
</div>
<div class="cards-container-new">
  <%= simple_form_for [@cocktail, @dose] do |f| %>

    <div class="form-inputs">
      <%= f.input :description %>
      <%= f.association :ingredient, input_html: { class: 'select2' } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
  <a>
  <%= link_to 'Cancel', @cocktail %>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <style>
      body {
        background-image: url(<%= image_path("cyberpunk.jpg") %>);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
        position: relative;
        /*z-index: 1;*/
        width: auto;
        height: auto;
        font-family: Orbitron;
        color: white;
        text-shadow: 8px 4px 8px #000000;
      }
    </style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="banner">
  <h1>Add Review</h1>
</div>
<div class="cards-container-new">
  <%= simple_form_for [@cocktail, @review] do |f| %>

    <div class="form-inputs">
      <%= f.input :content %>
      <%= f.button :submit %>
    </div>
  <% end %>
  <a>
  <%= link_to 'Cancel', @cocktail %>
  </a>
</div>